// @ts-nocheck
import * as __fd_glob_73 from "../content/docs/zh/workflows.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/zh/workflow-nodes-and-execution.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/zh/workflow-monitoring.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/zh/troubleshooting.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/zh/teams-and-collaboration.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/zh/team-model-authorization.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/zh/team-management.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/zh/system-administration.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/zh/sso-configuration.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/zh/site-settings-security.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/zh/roles-and-permissions.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/zh/prompt-generator.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/zh/platform-api.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/zh/notifications.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/zh/notification-channels.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/zh/models-and-tools.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/zh/model-management.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/zh/memories.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/zh/knowledge-documents-and-retrieval.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/zh/knowledge-base.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/zh/knowledge-base-optimization.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/zh/index.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/zh/getting-started.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/zh/file-management.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/zh/conversations-and-messages.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/zh/best-practices.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/zh/background-tasks.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/zh/authentication-and-sso.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/zh/audit-and-monitoring.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/zh/api-overview.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/zh/api-keys.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/zh/api-key-practices.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/zh/agents.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/zh/agent-capabilities.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/zh/admin-api.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/zh/accounts-and-access.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/en/workflows.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/en/workflow-nodes-and-execution.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/en/workflow-monitoring.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/en/troubleshooting.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/en/teams-and-collaboration.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/en/team-model-authorization.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/en/team-management.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/en/system-administration.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/en/sso-configuration.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/en/site-settings-security.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/en/roles-and-permissions.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/en/prompt-generator.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/en/platform-api.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/en/notifications.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/en/notification-channels.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/en/models-and-tools.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/en/model-management.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/en/memories.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/en/knowledge-documents-and-retrieval.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/en/knowledge-base.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/en/knowledge-base-optimization.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/en/index.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/en/getting-started.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/en/file-management.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/en/conversations-and-messages.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/en/best-practices.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/en/background-tasks.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/en/authentication-and-sso.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/en/audit-and-monitoring.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/en/api-overview.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/en/api-keys.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/en/api-key-practices.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/en/agents.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/en/agent-capabilities.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/en/admin-api.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/en/accounts-and-access.mdx?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/zh/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/en/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"en/meta.json": __fd_glob_0, "zh/meta.json": __fd_glob_1, }, {"en/accounts-and-access.mdx": __fd_glob_2, "en/admin-api.mdx": __fd_glob_3, "en/agent-capabilities.mdx": __fd_glob_4, "en/agents.mdx": __fd_glob_5, "en/api-key-practices.mdx": __fd_glob_6, "en/api-keys.mdx": __fd_glob_7, "en/api-overview.mdx": __fd_glob_8, "en/audit-and-monitoring.mdx": __fd_glob_9, "en/authentication-and-sso.mdx": __fd_glob_10, "en/background-tasks.mdx": __fd_glob_11, "en/best-practices.mdx": __fd_glob_12, "en/conversations-and-messages.mdx": __fd_glob_13, "en/file-management.mdx": __fd_glob_14, "en/getting-started.mdx": __fd_glob_15, "en/index.mdx": __fd_glob_16, "en/knowledge-base-optimization.mdx": __fd_glob_17, "en/knowledge-base.mdx": __fd_glob_18, "en/knowledge-documents-and-retrieval.mdx": __fd_glob_19, "en/memories.mdx": __fd_glob_20, "en/model-management.mdx": __fd_glob_21, "en/models-and-tools.mdx": __fd_glob_22, "en/notification-channels.mdx": __fd_glob_23, "en/notifications.mdx": __fd_glob_24, "en/platform-api.mdx": __fd_glob_25, "en/prompt-generator.mdx": __fd_glob_26, "en/roles-and-permissions.mdx": __fd_glob_27, "en/site-settings-security.mdx": __fd_glob_28, "en/sso-configuration.mdx": __fd_glob_29, "en/system-administration.mdx": __fd_glob_30, "en/team-management.mdx": __fd_glob_31, "en/team-model-authorization.mdx": __fd_glob_32, "en/teams-and-collaboration.mdx": __fd_glob_33, "en/troubleshooting.mdx": __fd_glob_34, "en/workflow-monitoring.mdx": __fd_glob_35, "en/workflow-nodes-and-execution.mdx": __fd_glob_36, "en/workflows.mdx": __fd_glob_37, "zh/accounts-and-access.mdx": __fd_glob_38, "zh/admin-api.mdx": __fd_glob_39, "zh/agent-capabilities.mdx": __fd_glob_40, "zh/agents.mdx": __fd_glob_41, "zh/api-key-practices.mdx": __fd_glob_42, "zh/api-keys.mdx": __fd_glob_43, "zh/api-overview.mdx": __fd_glob_44, "zh/audit-and-monitoring.mdx": __fd_glob_45, "zh/authentication-and-sso.mdx": __fd_glob_46, "zh/background-tasks.mdx": __fd_glob_47, "zh/best-practices.mdx": __fd_glob_48, "zh/conversations-and-messages.mdx": __fd_glob_49, "zh/file-management.mdx": __fd_glob_50, "zh/getting-started.mdx": __fd_glob_51, "zh/index.mdx": __fd_glob_52, "zh/knowledge-base-optimization.mdx": __fd_glob_53, "zh/knowledge-base.mdx": __fd_glob_54, "zh/knowledge-documents-and-retrieval.mdx": __fd_glob_55, "zh/memories.mdx": __fd_glob_56, "zh/model-management.mdx": __fd_glob_57, "zh/models-and-tools.mdx": __fd_glob_58, "zh/notification-channels.mdx": __fd_glob_59, "zh/notifications.mdx": __fd_glob_60, "zh/platform-api.mdx": __fd_glob_61, "zh/prompt-generator.mdx": __fd_glob_62, "zh/roles-and-permissions.mdx": __fd_glob_63, "zh/site-settings-security.mdx": __fd_glob_64, "zh/sso-configuration.mdx": __fd_glob_65, "zh/system-administration.mdx": __fd_glob_66, "zh/team-management.mdx": __fd_glob_67, "zh/team-model-authorization.mdx": __fd_glob_68, "zh/teams-and-collaboration.mdx": __fd_glob_69, "zh/troubleshooting.mdx": __fd_glob_70, "zh/workflow-monitoring.mdx": __fd_glob_71, "zh/workflow-nodes-and-execution.mdx": __fd_glob_72, "zh/workflows.mdx": __fd_glob_73, });